spring:
  application:
    name: be

  # Configuration for PostgreSQL database
  datasource:
    url: jdbc:postgresql://localhost:5432/sportsdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuration for OAuth2 clients (Google and Facebook)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
#          facebook:
#            client-id: ${FACEBOOK_CLIENT_ID}
#            client-secret: ${FACEBOOK_CLIENT_SECRET}
#            scope: public_profile, email
#            redirect-uri:
app:
  oauth2:
    # Sau khi người dùng đăng nhập thành công, họ sẽ được chuyển hướng đến URL này
    redirect-uri: http://localhost:5173/oauth2/redirect


  # Configuration for Cloudinary
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}