spring:
  application:
    name: be

  # Configuration for PostgreSQL database
  datasource:
    url: jdbc:postgresql://localhost:5432/sportsdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

